/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package gms.cims.bridge;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class ClaimStatus extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -6076373865953235505L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"ClaimStatus\",\"namespace\":\"gms.cims.bridge\",\"fields\":[{\"name\":\"CS_ClaimStatusID\",\"type\":\"int\"},{\"name\":\"CS_Description\",\"type\":[\"null\",\"string\"],\"default\":null}],\"connect.name\":\"CIMSTEST.Financial.ClaimStatus.Value\"}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<ClaimStatus> ENCODER =
      new BinaryMessageEncoder<ClaimStatus>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<ClaimStatus> DECODER =
      new BinaryMessageDecoder<ClaimStatus>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   */
  public static BinaryMessageDecoder<ClaimStatus> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   */
  public static BinaryMessageDecoder<ClaimStatus> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<ClaimStatus>(MODEL$, SCHEMA$, resolver);
  }

  /** Serializes this ClaimStatus to a ByteBuffer. */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /** Deserializes a ClaimStatus from a ByteBuffer. */
  public static ClaimStatus fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  @Deprecated public int CS_ClaimStatusID;
  @Deprecated public java.lang.CharSequence CS_Description;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public ClaimStatus() {}

  /**
   * All-args constructor.
   * @param CS_ClaimStatusID The new value for CS_ClaimStatusID
   * @param CS_Description The new value for CS_Description
   */
  public ClaimStatus(java.lang.Integer CS_ClaimStatusID, java.lang.CharSequence CS_Description) {
    this.CS_ClaimStatusID = CS_ClaimStatusID;
    this.CS_Description = CS_Description;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return CS_ClaimStatusID;
    case 1: return CS_Description;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: CS_ClaimStatusID = (java.lang.Integer)value$; break;
    case 1: CS_Description = (java.lang.CharSequence)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'CS_ClaimStatusID' field.
   * @return The value of the 'CS_ClaimStatusID' field.
   */
  public java.lang.Integer getCSClaimStatusID() {
    return CS_ClaimStatusID;
  }

  /**
   * Sets the value of the 'CS_ClaimStatusID' field.
   * @param value the value to set.
   */
  public void setCSClaimStatusID(java.lang.Integer value) {
    this.CS_ClaimStatusID = value;
  }

  /**
   * Gets the value of the 'CS_Description' field.
   * @return The value of the 'CS_Description' field.
   */
  public java.lang.CharSequence getCSDescription() {
    return CS_Description;
  }

  /**
   * Sets the value of the 'CS_Description' field.
   * @param value the value to set.
   */
  public void setCSDescription(java.lang.CharSequence value) {
    this.CS_Description = value;
  }

  /**
   * Creates a new ClaimStatus RecordBuilder.
   * @return A new ClaimStatus RecordBuilder
   */
  public static gms.cims.bridge.ClaimStatus.Builder newBuilder() {
    return new gms.cims.bridge.ClaimStatus.Builder();
  }

  /**
   * Creates a new ClaimStatus RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new ClaimStatus RecordBuilder
   */
  public static gms.cims.bridge.ClaimStatus.Builder newBuilder(gms.cims.bridge.ClaimStatus.Builder other) {
    return new gms.cims.bridge.ClaimStatus.Builder(other);
  }

  /**
   * Creates a new ClaimStatus RecordBuilder by copying an existing ClaimStatus instance.
   * @param other The existing instance to copy.
   * @return A new ClaimStatus RecordBuilder
   */
  public static gms.cims.bridge.ClaimStatus.Builder newBuilder(gms.cims.bridge.ClaimStatus other) {
    return new gms.cims.bridge.ClaimStatus.Builder(other);
  }

  /**
   * RecordBuilder for ClaimStatus instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<ClaimStatus>
    implements org.apache.avro.data.RecordBuilder<ClaimStatus> {

    private int CS_ClaimStatusID;
    private java.lang.CharSequence CS_Description;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(gms.cims.bridge.ClaimStatus.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.CS_ClaimStatusID)) {
        this.CS_ClaimStatusID = data().deepCopy(fields()[0].schema(), other.CS_ClaimStatusID);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.CS_Description)) {
        this.CS_Description = data().deepCopy(fields()[1].schema(), other.CS_Description);
        fieldSetFlags()[1] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing ClaimStatus instance
     * @param other The existing instance to copy.
     */
    private Builder(gms.cims.bridge.ClaimStatus other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.CS_ClaimStatusID)) {
        this.CS_ClaimStatusID = data().deepCopy(fields()[0].schema(), other.CS_ClaimStatusID);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.CS_Description)) {
        this.CS_Description = data().deepCopy(fields()[1].schema(), other.CS_Description);
        fieldSetFlags()[1] = true;
      }
    }

    /**
      * Gets the value of the 'CS_ClaimStatusID' field.
      * @return The value.
      */
    public java.lang.Integer getCSClaimStatusID() {
      return CS_ClaimStatusID;
    }

    /**
      * Sets the value of the 'CS_ClaimStatusID' field.
      * @param value The value of 'CS_ClaimStatusID'.
      * @return This builder.
      */
    public gms.cims.bridge.ClaimStatus.Builder setCSClaimStatusID(int value) {
      validate(fields()[0], value);
      this.CS_ClaimStatusID = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'CS_ClaimStatusID' field has been set.
      * @return True if the 'CS_ClaimStatusID' field has been set, false otherwise.
      */
    public boolean hasCSClaimStatusID() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'CS_ClaimStatusID' field.
      * @return This builder.
      */
    public gms.cims.bridge.ClaimStatus.Builder clearCSClaimStatusID() {
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'CS_Description' field.
      * @return The value.
      */
    public java.lang.CharSequence getCSDescription() {
      return CS_Description;
    }

    /**
      * Sets the value of the 'CS_Description' field.
      * @param value The value of 'CS_Description'.
      * @return This builder.
      */
    public gms.cims.bridge.ClaimStatus.Builder setCSDescription(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.CS_Description = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'CS_Description' field has been set.
      * @return True if the 'CS_Description' field has been set, false otherwise.
      */
    public boolean hasCSDescription() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'CS_Description' field.
      * @return This builder.
      */
    public gms.cims.bridge.ClaimStatus.Builder clearCSDescription() {
      CS_Description = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public ClaimStatus build() {
      try {
        ClaimStatus record = new ClaimStatus();
        record.CS_ClaimStatusID = fieldSetFlags()[0] ? this.CS_ClaimStatusID : (java.lang.Integer) defaultValue(fields()[0]);
        record.CS_Description = fieldSetFlags()[1] ? this.CS_Description : (java.lang.CharSequence) defaultValue(fields()[1]);
        return record;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<ClaimStatus>
    WRITER$ = (org.apache.avro.io.DatumWriter<ClaimStatus>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<ClaimStatus>
    READER$ = (org.apache.avro.io.DatumReader<ClaimStatus>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
