/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */

import org.apache.avro.specific.SpecificData;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class ClaimBlackList extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -6930175803268641802L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"ClaimBlackList\",\"fields\":[{\"name\":\"CO_ContractID\",\"type\":\"int\"},{\"name\":\"IsIndividual\",\"type\":\"boolean\"}],\"connect.name\":\"CIMSTEST.Customer.ClaimBlackList.Value\"}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<ClaimBlackList> ENCODER =
      new BinaryMessageEncoder<ClaimBlackList>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<ClaimBlackList> DECODER =
      new BinaryMessageDecoder<ClaimBlackList>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   */
  public static BinaryMessageDecoder<ClaimBlackList> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   */
  public static BinaryMessageDecoder<ClaimBlackList> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<ClaimBlackList>(MODEL$, SCHEMA$, resolver);
  }

  /** Serializes this ClaimBlackList to a ByteBuffer. */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /** Deserializes a ClaimBlackList from a ByteBuffer. */
  public static ClaimBlackList fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  @Deprecated public int CO_ContractID;
  @Deprecated public boolean IsIndividual;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public ClaimBlackList() {}

  /**
   * All-args constructor.
   * @param CO_ContractID The new value for CO_ContractID
   * @param IsIndividual The new value for IsIndividual
   */
  public ClaimBlackList(java.lang.Integer CO_ContractID, java.lang.Boolean IsIndividual) {
    this.CO_ContractID = CO_ContractID;
    this.IsIndividual = IsIndividual;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return CO_ContractID;
    case 1: return IsIndividual;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: CO_ContractID = (java.lang.Integer)value$; break;
    case 1: IsIndividual = (java.lang.Boolean)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'CO_ContractID' field.
   * @return The value of the 'CO_ContractID' field.
   */
  public java.lang.Integer getCOContractID() {
    return CO_ContractID;
  }

  /**
   * Sets the value of the 'CO_ContractID' field.
   * @param value the value to set.
   */
  public void setCOContractID(java.lang.Integer value) {
    this.CO_ContractID = value;
  }

  /**
   * Gets the value of the 'IsIndividual' field.
   * @return The value of the 'IsIndividual' field.
   */
  public java.lang.Boolean getIsIndividual() {
    return IsIndividual;
  }

  /**
   * Sets the value of the 'IsIndividual' field.
   * @param value the value to set.
   */
  public void setIsIndividual(java.lang.Boolean value) {
    this.IsIndividual = value;
  }

  /**
   * Creates a new ClaimBlackList RecordBuilder.
   * @return A new ClaimBlackList RecordBuilder
   */
  public static ClaimBlackList.Builder newBuilder() {
    return new ClaimBlackList.Builder();
  }

  /**
   * Creates a new ClaimBlackList RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new ClaimBlackList RecordBuilder
   */
  public static ClaimBlackList.Builder newBuilder(ClaimBlackList.Builder other) {
    return new ClaimBlackList.Builder(other);
  }

  /**
   * Creates a new ClaimBlackList RecordBuilder by copying an existing ClaimBlackList instance.
   * @param other The existing instance to copy.
   * @return A new ClaimBlackList RecordBuilder
   */
  public static ClaimBlackList.Builder newBuilder(ClaimBlackList other) {
    return new ClaimBlackList.Builder(other);
  }

  /**
   * RecordBuilder for ClaimBlackList instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<ClaimBlackList>
    implements org.apache.avro.data.RecordBuilder<ClaimBlackList> {

    private int CO_ContractID;
    private boolean IsIndividual;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(ClaimBlackList.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.CO_ContractID)) {
        this.CO_ContractID = data().deepCopy(fields()[0].schema(), other.CO_ContractID);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.IsIndividual)) {
        this.IsIndividual = data().deepCopy(fields()[1].schema(), other.IsIndividual);
        fieldSetFlags()[1] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing ClaimBlackList instance
     * @param other The existing instance to copy.
     */
    private Builder(ClaimBlackList other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.CO_ContractID)) {
        this.CO_ContractID = data().deepCopy(fields()[0].schema(), other.CO_ContractID);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.IsIndividual)) {
        this.IsIndividual = data().deepCopy(fields()[1].schema(), other.IsIndividual);
        fieldSetFlags()[1] = true;
      }
    }

    /**
      * Gets the value of the 'CO_ContractID' field.
      * @return The value.
      */
    public java.lang.Integer getCOContractID() {
      return CO_ContractID;
    }

    /**
      * Sets the value of the 'CO_ContractID' field.
      * @param value The value of 'CO_ContractID'.
      * @return This builder.
      */
    public ClaimBlackList.Builder setCOContractID(int value) {
      validate(fields()[0], value);
      this.CO_ContractID = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'CO_ContractID' field has been set.
      * @return True if the 'CO_ContractID' field has been set, false otherwise.
      */
    public boolean hasCOContractID() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'CO_ContractID' field.
      * @return This builder.
      */
    public ClaimBlackList.Builder clearCOContractID() {
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'IsIndividual' field.
      * @return The value.
      */
    public java.lang.Boolean getIsIndividual() {
      return IsIndividual;
    }

    /**
      * Sets the value of the 'IsIndividual' field.
      * @param value The value of 'IsIndividual'.
      * @return This builder.
      */
    public ClaimBlackList.Builder setIsIndividual(boolean value) {
      validate(fields()[1], value);
      this.IsIndividual = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'IsIndividual' field has been set.
      * @return True if the 'IsIndividual' field has been set, false otherwise.
      */
    public boolean hasIsIndividual() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'IsIndividual' field.
      * @return This builder.
      */
    public ClaimBlackList.Builder clearIsIndividual() {
      fieldSetFlags()[1] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public ClaimBlackList build() {
      try {
        ClaimBlackList record = new ClaimBlackList();
        record.CO_ContractID = fieldSetFlags()[0] ? this.CO_ContractID : (java.lang.Integer) defaultValue(fields()[0]);
        record.IsIndividual = fieldSetFlags()[1] ? this.IsIndividual : (java.lang.Boolean) defaultValue(fields()[1]);
        return record;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<ClaimBlackList>
    WRITER$ = (org.apache.avro.io.DatumWriter<ClaimBlackList>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<ClaimBlackList>
    READER$ = (org.apache.avro.io.DatumReader<ClaimBlackList>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
